services:
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - sipv
    volumes: 
      - ./mongo/dump:/dump:ro
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    networks:
      - sipv
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
   
    depends_on:
      mongo:
          condition: service_healthy
  web:
    container_name: express_web
    build: .
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    depends_on:
        mongo:
          condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - sipv
    env_file: ".env"
networks:
    sipv:
      name: sipv_backend